### ISSUE TITLE
prettyping

### ISSUE THREAD

**Issue by denilsonsa** [hcartiaux/archlinux-packages#1]
I've just moved `prettyping` to its own repository. You might want to update the PKGBUILD. And thanks for creating this package!

https://github.com/denilsonsa/prettyping
http://denilsonsa.github.io/prettyping/

**Comment by hcartiaux** [comment]
You're welcome. There is a new package in AUR4 for prettyping: https://aur.archlinux.org/packages/prettyping/ 
The new package uses the sources from your git repo.
